services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    
    restart: always

volumes:
  postgres_data: